### PR TITLE
Stable to final stable

### PR DESCRIPTION
**Pull request by SofiBretz**

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Work @SofiBretz  :clap: :clap:. Unfortunately, some requirements that prevents your project's approval needs to be implemented. check below :arrow_down:  

#### Page structure

##### Main content

* [ ] **It changes with RWD breakpoints.**
image
> **Below screen width of 580px you page becomes as above. Each of the sections should occupy the full width of the page at that width**
- there is also an horizontal scroll there also, kindly take care of it :pray: 

#### Implementation details

* [ ] It uses Bootstrap Css classes **everywhere** for styling ( for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options) )
- **You are supposed to use bootstrap default class as much as possible. Include them in your html :skull:** . 
- **You css files contains a lot of customized styling, the point of this project is  to understand how frameworks generally works and how you can take the most from them. You should delete any css code that act on the layout, the positioning and the responsiveness of the page's content, they all can be done using bootstrap :no_entry_sign: .**

#### General Requirements:

* [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

### That's it :relieved: . When finished, kindly resubmit another code review request :pray: .

**Comment by SofiBretz** [comment]
Validator w3 and stickler on green, Bootstrap requirement fixed, width of 580px fixed. Thank you! :)

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great progress so far :clap: . However there is some minor issues that you need to pay attention to. check below :arrow_down: 

##### Main content
- The new arrangement is good, except the problem of the **horizontal scroll** still present. I think some of you image are too wide and they are causing the horizontal scroll.

- I checked you css files, I still find some media queries, responsiveness in this project is totally feasible using bootstrap default classes :nerd_face: . Please work you way arround using them :pray: 

### That's it :relieved: . You're almost there :muscle: . When finished, kindly resubmit another code review request :pray:

**Comment by SofiBretz** [comment]
Advices check it :) I used Bootstrap in the whole project, advices fixed ;) thank you!

**Review by Oghenebrume50 — APPROVED** [review]
Hi @SofiBretz this is good everything works fine. **This is approved**

**Comment by SofiBretz** [comment]
Thank you! :)

**Pull request merged**
